# Generated by Django 4.1 on 2024-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="app_icon",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
